services:
  frontend:
    build:
      context: .
    ports:
      - "${FRONT_PORT:-3001}:3000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: "development"
    networks:
      - app-network
    volumes:
      - ./:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:

networks:
  app-network:
    external: true
    name: app-network
